# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{heroku_deploy}
  s.version = "0.1.10"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Ross Hale"]
  s.date = %q{2010-09-20}
  s.description = %q{Deploy strategy and scripts for Heroku.}
  s.email = %q{rosshale@gmail.com}
  s.extra_rdoc_files = [
    "README.markdown"
  ]
  s.files = [
    ".gitignore",
     "Gemfile",
     "Gemfile.lock",
     "README.markdown",
     "Rakefile",
     "VERSION",
     "heroku_deploy.gemspec",
     "lib/heroku_deploy.rb",
     "lib/heroku_deploy/tasks.rb",
     "test/heroku_deploy_test.rb",
     "test/test_helper.rb"
  ]
  s.homepage = %q{http://github.com/lottay/heroku_deploy}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{initial import}
  s.test_files = [
    "test/heroku_deploy_test.rb",
     "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

